"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, Folder, LayoutList, Map, Radio, Search, Sparkles, TriangleAlert } from "lucide-react";
import { useConstellationStore } from "@/lib/store/useConstellationStore";
import type { ViewMode } from "@/lib/types";
import styles from "./CommandPalette.module.css";

export interface CommandPaletteProps { open?: boolean; onOpenChange?: (open: boolean) => void; onNewAgent?: () => void; onAddFolder?: () => void; onShowAttention?: () => void; onFitOverview?: () => void; }

export function CommandPalette({ open: controlledOpen, onOpenChange, onNewAgent, onAddFolder, onShowAttention, onFitOverview }: CommandPaletteProps) {
  const [internalOpen, setInternalOpen] = useState(false); const [query, setQuery] = useState(""); const [active, setActive] = useState(0); const inputRef = useRef<HTMLInputElement>(null);
  const open = controlledOpen ?? internalOpen; const setOpen = (value: boolean) => { if (controlledOpen === undefined) setInternalOpen(value); onOpenChange?.(value); };
  const folders = useConstellationStore((s) => s.folders); const threads = useConstellationStore((s) => s.threads); const selectFolder = useConstellationStore((s) => s.selectFolder); const selectThread = useConstellationStore((s) => s.selectThread); const setViewMode = useConstellationStore((s) => s.setViewMode); const storeSetQuery = useConstellationStore((s) => s.setQuery);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { const modifier = event.metaKey || event.ctrlKey; if (modifier && (event.key.toLowerCase() === "k" || (event.shiftKey && event.key.toLowerCase() === "o"))) { event.preventDefault(); setOpen(!open); } if (event.key === "Escape" && open) setOpen(false); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [open]);
  useEffect(() => { if (open) { setQuery(""); storeSetQuery(""); setActive(0); requestAnimationFrame(() => inputRef.current?.focus()); } }, [open, storeSetQuery]);
  const needle = query.trim().toLowerCase();
  const results = useMemo(() => { const folderResults = Object.values(folders).filter((f) => !needle || `${f.name} ${f.path}`.toLowerCase().includes(needle)).slice(0, 6).map((f) => ({ id: `folder-${f.id}`, label: f.name, detail: `PROJECT · ${f.path}`, icon: <Folder />, run: () => { storeSetQuery(""); selectFolder(f.id); setOpen(false); } })); const threadResults = Object.values(threads).filter((t) => { const provider = t.provider === "claude" ? "Claude Code" : "Codex"; return !t.archived && (!needle || `${t.key} ${t.title} ${t.objective} ${t.summary} ${t.profile} ${t.branch ?? ""} ${provider} ${folders[t.folderId]?.name ?? ""}`.toLowerCase().includes(needle)); }).slice(0, 12).map((t) => ({ id: `thread-${t.id}`, label: t.title, detail: `${t.provider === "claude" ? "CLAUDE" : "CODEX"} · ${t.key} · ${folders[t.folderId]?.name ?? "Unknown folder"} · ${t.status.replace("_", " ")}`, icon: <Sparkles />, run: () => { storeSetQuery(""); selectFolder(t.folderId); selectThread(t.id); setOpen(false); } })); return [...folderResults, ...threadResults]; }, [folders, threads, needle, selectFolder, selectThread, storeSetQuery]);
  const commands = [{ id: "new-agent", label: "New agent", detail: "Create a main task", icon: <Sparkles />, run: () => { onNewAgent?.(); setOpen(false); } }, { id: "add-folder", label: "Add folder", detail: "Connect a project context", icon: <Folder />, run: () => { onAddFolder?.(); setOpen(false); } }, { id: "attention", label: "Show attention", detail: "Open approvals and errors", icon: <TriangleAlert />, run: () => { onShowAttention?.(); setOpen(false); } }, { id: "overview", label: "Fit map overview", detail: "See every folder", icon: <Map />, run: () => { onFitOverview?.(); setOpen(false); } }, ...(["now", "map", "list", "activity"] as ViewMode[]).map((mode) => ({ id: `view-${mode}`, label: `Switch to ${mode}`, detail: "Change workspace view", icon: mode === "now" ? <Radio /> : mode === "map" ? <Map /> : mode === "list" ? <LayoutList /> : <Activity />, run: () => { setViewMode(mode); setOpen(false); } }))].filter((command) => !needle || `${command.label} ${command.detail}`.toLowerCase().includes(needle));
  const items = [...results, ...commands];
  useEffect(() => setActive((current) => Math.min(current, Math.max(0, items.length - 1))), [items.length]);
  if (!open) return null;
  return <div className={styles.scrim} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section className={styles.palette} role="dialog" aria-modal="true" aria-labelledby="palette-title"><h2 id="palette-title" className={styles.srOnly}>Quick jump and command palette</h2><div className={styles.search}><Search aria-hidden="true" /><input ref={inputRef} value={query} onChange={(event) => { setQuery(event.target.value); storeSetQuery(event.target.value); setActive(0); }} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setActive((x) => Math.min(x + 1, items.length - 1)); } else if (event.key === "ArrowUp") { event.preventDefault(); setActive((x) => Math.max(x - 1, 0)); } else if (event.key === "Enter" && items[active]) items[active].run(); }} placeholder="Jump to any project or task…" aria-label="Jump to a project or task, or search commands" /><kbd>ESC</kbd></div><div className={styles.results} role="listbox" aria-label="Quick jump results">{items.length ? items.map((item, index) => <button key={item.id} className={index === active ? styles.resultActive : styles.result} onMouseEnter={() => setActive(index)} onClick={item.run} role="option" aria-selected={index === active}><span className={styles.resultIcon}>{item.icon}</span><span><strong>{item.label}</strong><small>{item.detail}</small></span><span className={styles.enter}>{index === active ? "↵" : ""}</span></button>) : <p className={styles.empty}>No matching projects, tasks, or commands.</p>}</div><footer><span><kbd>↑↓</kbd> navigate</span><span><kbd>↵</kbd> jump</span><span><kbd>⌘⇧O</kbd> quick jump</span><span><kbd>⌘K</kbd> commands</span></footer></section></div>;
}
