const fs = require('node:fs');
const path = require('node:path');
const { atomicWrite } = require('./state.cjs');
function scalar(value) { const s = String(value ?? '').trim(); if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) return s.slice(1, -1); if (s === 'true' || s === 'false') return s === 'true'; if (/^-?\d+(\.\d+)?$/.test(s)) return Number(s); return s; }
function parseFrontmatter(markdown) { if (!markdown.startsWith('---')) return {}; const end = markdown.search(/\r?\n---(?:\r?\n|$)/); if (end < 0) return {}; const result = {}; let key; markdown.slice(4, end).split(/\r?\n/).forEach((line) => { const m = line.match(/^\s*([\w-]+):\s*(.*)$/); if (m) { key = m[2] ? undefined : m[1]; result[m[1]] = m[2] ? scalar(m[2]) : []; } else if (key && /^\s*-\s+/.test(line)) result[key].push(scalar(line.replace(/^\s*-\s+/, ''))); }); return result; }
function splitMarkdown(markdown) { const end = markdown.startsWith('---') ? markdown.search(/\r?\n---(?:\r?\n|$)/) : -1; return end < 0 ? { metadata: {}, body: markdown, hasFrontmatter: false } : { metadata: parseFrontmatter(markdown), body: markdown.slice(end + markdown.slice(end).match(/^\r?\n---\s*/)[0].length), hasFrontmatter: true }; }
function list(value) { if (Array.isArray(value)) return value.map(String); if (!value) return []; return String(value).split(',').map((v) => v.trim()).filter(Boolean); }
function parseTicket(filePath, markdown) { const { metadata, body } = splitMarkdown(markdown); const lines = body.split(/\r?\n/); const heading = lines.find((l) => /^#\s+/.test(l)); const criteria = lines.map((line, i) => { const m = line.match(/^\s*[-*]\s+\[([ xX])\]\s+(.+)$/); return m ? { text: m[2].trim(), completed: m[1].toLowerCase() === 'x', line: i + 1 } : null; }).filter(Boolean); const root = path.resolve(filePath).split(`${path.sep}.tickets${path.sep}`)[0]; const state = String(metadata.state || metadata.status || (criteria.length && criteria.every((x) => x.completed) ? 'done' : 'todo')).toLowerCase(); return { ...metadata, id: String(metadata.id || path.basename(filePath, '.md')), title: String(metadata.title || (heading ? heading.slice(1).trim() : path.basename(filePath, '.md'))), objective: String(metadata.objective || lines.filter((l) => l.trim() && !/^#/.test(l) && !/^\s*[-*]\s+\[/.test(l)).slice(0, 4).join(' ').trim()), parent: metadata.parent || metadata.parentId || null, parentId: metadata.parentId || metadata.parent || null, blockedBy: list(metadata.blockedBy), assignee: metadata.assignee || null, state, status: state, cwd: root, filePath: path.resolve(filePath), acceptanceCriteria: criteria, progress: { completed: criteria.filter((x) => x.completed).length, total: criteria.length }, updatedAt: fs.statSync(filePath).mtime.toISOString(), body }; }
function replaceMetadata(markdown, patch) { const split = splitMarkdown(markdown); const metadata = { ...split.metadata, ...patch }; const lines = Object.entries(metadata).filter(([, v]) => v !== undefined && v !== null).flatMap(([key, value]) => Array.isArray(value) ? [`${key}:`, ...value.map((item) => `  - ${String(item)}`)] : [`${key}: ${typeof value === 'string' && /[:#]/.test(value) ? JSON.stringify(value) : String(value)}`]); return `---\n${lines.join('\n')}\n---\n${split.body.replace(/^\r?\n/, '')}`; }
function updateTicketAtomic(filePath, patch) { const current = fs.readFileSync(filePath, 'utf8'); const ticket = parseTicket(filePath, current); const next = {}; ['title', 'objective', 'parent', 'parentId', 'blockedBy', 'assignee', 'state'].forEach((key) => { if (patch[key] !== undefined) next[key] = patch[key]; }); if (next.parent !== undefined && next.parentId === undefined) next.parentId = next.parent; if (next.parentId !== undefined && next.parent === undefined) next.parent = next.parentId; let markdown = replaceMetadata(current, next); if (patch.acceptanceCriteria !== undefined) { const requested = patch.acceptanceCriteria.map((item, index) => { const value = typeof item === 'object' ? item : { text: item }; const previous = ticket.acceptanceCriteria[index]; return { text: String(value.text), completed: value.completed === undefined ? Boolean(previous?.completed) : Boolean(value.completed) }; }); let index = 0; markdown = markdown.split(/\r?\n/).map((line) => { if (!/^\s*[-*]\s+\[[ xX]\]\s+/.test(line) || !requested[index]) return line; const item = requested[index++]; return line.replace(/^(\s*[-*]\s+)\[[ xX]\](\s+).*/, `$1[${item.completed ? 'x' : ' '}]$2${item.text}`); }).join('\n'); } atomicWriteText(filePath, markdown); return parseTicket(filePath, fs.readFileSync(filePath, 'utf8')); }
function atomicWriteText(file, value) { fs.mkdirSync(path.dirname(file), { recursive: true }); const tmp = `${file}.${process.pid}.${Date.now()}.tmp`; fs.writeFileSync(tmp, value, 'utf8'); fs.renameSync(tmp, file); }
module.exports = { parseFrontmatter, splitMarkdown, parseTicket, replaceMetadata, updateTicketAtomic, atomicWriteText };
